name: Build Mobile Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Generate Android platform files
        run: |
          cd mobile
          flutter create --platforms android . --project-name master_help

      - name: Get Flutter dependencies
        run: |
          cd mobile
          flutter pub get

      - name: Build Android APK
        run: |
          cd mobile
          flutter build apk --release --no-pub
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Avtohelp-MasterHelp-Release-APK
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: warn
